# Generated by Django 6.0.5 on 2026-06-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentikate", "0005_alter_client_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="identifier",
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="release",
            unique_together={("app", "version")},
        ),
    ]
