# Generated by Django 6.0.5 on 2026-09-26 07:38

from django.db import migrations, models
from django.db.models import F


def move_username_off_first_name(apps, schema_editor):
    """Before 0007 the token's preferred_username was stored on first_name.

    Move it to its own column, give first_name back its meaning (given_name), and reset
    changed_hash so each user's full profile is re-synced from their next token.
    """
    User = apps.get_model("authentikate", "User")
    User.objects.update(preferred_username=F("first_name"), first_name="", changed_hash=None)


class Migration(migrations.Migration):

    dependencies = [
        ("authentikate", "0006_alter_app_identifier_alter_release_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="locale",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_username",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="user",
            name="zoneinfo",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RunPython(move_username_off_first_name, migrations.RunPython.noop),
    ]
