name: CI
on:
  push:
    branches: [main]
    paths: [authentikate/**, tests/**]
  pull_request:
    branches: [main]
    paths: [authentikate/**, tests/**]
jobs:
  mac_and_windows_unit:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        poetry-version: [1.7]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Run Poetry Install
        run: poetry install --all-extras
      - name: Run Tests
        run: poetry run pytest --cov --cov-report=xml 
  linux_unit:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        poetry-version: [1.7]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: ':99.0'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
     - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Run Poetry Install
        run: poetry install --all-extras
      - name: Run Tests
        run: poetry run pytest --cov --cov-report=xml 
  linux_integration:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
        poetry-version: [1.4]
        os: [ubuntu-latest]
    env:
      DISPLAY: ':99.0'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Run Poetry Install
        run: poetry install --all-extras
      - name: Run Tests
        run: poetry run pytest --cov --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
